### ISSUE TITLE
ModuleNotFoundError: No module named 'LoadPairs'

### ISSUE THREAD

**Issue by ahmedahmedov** [anfederico/pypoloniex#5]
Installed with pip. It seems this version is changed.

**Comment by ahmedahmedov** [comment]
When trying to install thru git using the following command:
`pip install git+https://github.com/Crypto-AI/pypoloniex
`
I get the following error:

`ERROR: unknown command "instal" - maybe you meant "install"
(py3) ahmed@ahmed-dwtc:~/anaconda3/envs/py3/lib/python3.6/site-packages/stocktalk$ pip install git+https://github.com/Crypto-AI/pypoloniex
Collecting git+https://github.com/Crypto-AI/pypoloniex
  Cloning https://github.com/Crypto-AI/pypoloniex to /tmp/pip-gku_271b-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/anaconda3/envs/py3/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-gku_271b-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-gku_271b-build/`

**Comment by Draichi** [comment]
same here, i installed via pip

**Comment by victorpy** [comment]
one fix for python3 will be to modify the file __init__.py and change the following:
Original
from LoadPairs import LoadPairs
Changed
from .LoadPairs import LoadPairs

**Comment by anfederico** [comment]
Install through Github, I haven't updated the package on PyPi. If someone wants to upgrade it to Python 3 feel free to submit a pull request.

I'm surprised people are still using this package.
